---
# tasks file for setup-lit
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_packages }}"

- name: Uninstall packages
  when: uninstall_packages != ""
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ uninstall_packages }}"

- name: Add some user
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
  with_items: "{{ add_users }}"

# code: language=ansible
